name: Pipeline Pull Request

on:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt
        pip install -r requirements.txt
    - name: Run lint
      run: |
        make lint
    - name: Run test coverage
      run: |
        make test-coverage

